src/Ibw/JobeetBundle/Form/JobType.php
<?php

namespace Ibw\JobeetBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Ibw\JobeetBundle\Entity\Job;

class JobType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('type', 'choice', array('choices' => Job::getTypes(), 'expanded' => true))
            ->add('category')
            ->add('company')
            ->add('logo', null, array('label' => 'Company logo'))
            ->add('url')
            ->add('position')
            ->add('location')
            ->add('description')
            ->add('how_to_apply', null, array('label' => 'How to apply?'))
            ->add('is_public', null, array('label' => 'Public?'))
            ->add('email')
            ->add('file', 'file', array('label' => 'Company logo', 'required' => false))
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Ibw\JobeetBundle\Entity\Job'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'job';
        //return 'ibw_jobeetbundle_job';
    }
}

src/Ibw/JobeetBundle/Controller/JobController.php
<?php

namespace Ibw\JobeetBundle\Controller;

use Ibw\JobeetBundle\Entity\Category;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use Ibw\JobeetBundle\Entity\Job;
use Ibw\JobeetBundle\Form\JobType;

/**
 * Job controller.
 *
 */
class JobController extends Controller
{

    /**
     * Lists all Job entities.
     *
     */
    public function indexAction()
    {

        $em = $this->getDoctrine()->getManager();
        //$entities = $em->getRepository('IbwJobeetBundle:Job')->getActiveJobs();
        $categories = $em->getRepository('IbwJobeetBundle:Category')->getWithJobs();

        foreach ($categories as $category) {
            $category->setActiveJobs($em->getRepository('IbwJobeetBundle:Job')->getActiveJobs($category->getId(), $this->container->
            getParameter('max_jobs_on_homepage')));

            $category->setMoreJobs($em->getRepository('IbwJobeetBundle:Job')->
                countActiveJobs($category->getId()) - $this->container->getParameter('max_jobs_on_homepage'));

        }

        return $this->render('IbwJobeetBundle:Job:index.html.twig', array(
            'categories' => $categories,
        ));
    }

    /**
     * Creates a new Job entity.
     *
     */
    public function createAction(Request $request)
    {

        $entity = new Job();
        $form = $this->createForm(new JobType(), $entity);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            //$entity->file->move(__DIR__.'/../../../../web/uploads/jobs', $entity->file->getClientOriginalName());
            //$entity->setLogo($entity->file->getClientOriginalName());

            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('ibw_job_preview', array(
                'company' => $entity->getCompanySlug(),
                'location' => $entity->getLocationSlug(),
                'token' => $entity->getToken(),
                'position' => $entity->getPositionSlug()
            )));
        }

        return $this->render('IbwJobeetBundle:Job:new.html.twig', array(
            'entity' => $entity,
            'form' => $form->createView(),
        ));
    }

    /**
     * Creates a form to create a Job entity.
     *
     * @param Job $entity The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createCreateForm(Job $entity)
    {
        $form = $this->createForm(new JobType(), $entity, array(
            'action' => $this->generateUrl('ibw_job_create'),
            'method' => 'POST',
        ));

        $form->add('submit', 'submit', array('label' => 'Create'));

        return $form;
    }

    /**
     * Displays a form to create a new Job entity.
     *
     */
    public function newAction()
    {
        $entity = new Job();
        $entity->setType('full-time');
        $form = $this->createForm(new JobType(), $entity);

        return $this->render('IbwJobeetBundle:Job:new.html.twig', array(
            'entity' => $entity,
            'form' => $form->createView(),
        ));
    }

    /**
     * Finds and displays a Job entity.
     *
     */
    public function showAction($id)
    {

        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('IbwJobeetBundle:Job')->getActiveJob($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Job entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        return $this->render('IbwJobeetBundle:Job:show.html.twig', array(
            'entity' => $entity,
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Displays a form to edit an existing Job entity.
     *
     */
    public function editAction($token)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('IbwJobeetBundle:Job')->findOneByToken($token);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Job entity.');
        }

        if ($entity->getIsActivated()) {
            throw $this->createNotFoundException('Job is activated and cannot be edited.');
        }
        $editForm = $this->createForm(new JobType(), $entity);
        $deleteForm = $this->createDeleteForm($token);

        return $this->render('IbwJobeetBundle:Job:edit.html.twig', array(
            'entity' => $entity,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Creates a form to edit a Job entity.
     *
     * @param Job $entity The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createEditForm(Job $entity)
    {
        $form = $this->createForm(new JobType(), $entity, array(
            'action' => $this->generateUrl('ibw_job_update', array('id' => $entity->getId())),
            'method' => 'PUT',
        ));

        $form->add('submit', 'submit', array('label' => 'Update'));

        return $form;
    }

    /**
     * Edits an existing Job entity.
     *
     */
    public function updateAction($token, Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('IbwJobeetBundle:Job')->findOneByToken($token);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Job entity.');
        }

        $editForm = $this->createForm(new JobType(), $entity);
        $deleteForm = $this->createDeleteForm($token);

        $editForm->handleRequest($request);

        if ($editForm->isValid()) {
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('ibw_job_preview', array(
                'company' => $entity->getCompanySlug(),
                'location' => $entity->getLocationSlug(),
                'token' => $entity->getToken(),
                'position' => $entity->getPositionSlug()
            )));
        }

        return $this->render('IbwJobeetBundle:Job:edit.html.twig', array(
            'entity' => $entity,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Deletes a Job entity.
     *
     */
    public function deleteAction($token, Request $request )
    {
        $form = $this->createDeleteForm($token);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('IbwJobeetBundle:Job')->findOneByToken($token);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find Job entity.');
            }

            $em->remove($entity);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('ibw_job'));
    }

    /**
     * Creates a form to delete a Job entity by id.
     *
     * @param mixed $id The entity id
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm($token)
    {
        return $this->createFormBuilder(array('token' => $token))
            ->add('token', 'hidden')
            ->getForm();
    }

    public function previewAction($token)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('IbwJobeetBundle:Job')->findOneByToken($token);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Job entity.');
        }

        $deleteForm = $this->createDeleteForm($entity->getToken());
        $publishForm = $this->createPublishForm($entity->getToken());
        $extendForm = $this->createExtendForm($entity->getToken());

        return $this->render('IbwJobeetBundle:Job:show.html.twig', array(
            'entity'      => $entity,
            'delete_form' => $deleteForm->createView(),
            'publish_form' => $publishForm->createView(),
            'extend_form' => $extendForm->createView(),
        ));
    }

    private function createPublishForm($token)
    {
        return $this->createFormBuilder(array('token' => $token))
            ->add('token', 'hidden')
            ->getForm()
            ;
    }


    public function publishAction(Request $request, $token)
    {
        $form = $this->createPublishForm($token);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('IbwJobeetBundle:Job')->findOneByToken($token);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find Job entity.');
            }

            $entity->publish();
            $em->persist($entity);
            $em->flush();

            $this->get('session')->getFlashBag()->add('notice', 'Your job is now online for 30 days.');
        }

        return $this->redirect($this->generateUrl('ibw_job_preview', array(
            'company' => $entity->getCompanySlug(),
            'location' => $entity->getLocationSlug(),
            'token' => $entity->getToken(),
            'position' => $entity->getPositionSlug()
        )));
    }

    public function extendAction(Request $request, $token)
    {
        $form = $this->createExtendForm($token);
        $request = $this->getRequest();

        $form->bind($request);

        if($form->isValid()) {
            $em=$this->getDoctrine()->getManager();
            $entity = $em->getRepository('IbwJobeetBundle:Job')->findOneByToken($token);

            if(!$entity){
                throw $this->createNotFoundException('Unable to find Job entity.');
            }

            if(!$entity->extend()){
                throw $this->createNodFoundException('Unable to extend the Job');
            }

src/Ibw/JobeetBundle/Resources/views/Job/admin.html.twig
<div id="job_actions">
    <h3>Admin</h3>
    <ul>
        {% if not job.isActivated %}
            <li><a href="{{ path('ibw_job_edit', { 'token': job.token }) }}">Edit</a></li>
            <li>
                <form action="{{ path('ibw_job_publish', { 'token': job.token }) }}" method="post">
                    {{ form_widget(publish_form) }}
                    <button type="submit">Publish</button>
                </form>
            </li>
        {% endif %}
        <li>
            <form action="{{ path('ibw_job_delete', { 'token': job.token }) }}" method="post">
                {{ form_widget(delete_form) }}
                <button type="submit" onclick="if(!confirm('Are you sure?')) { return false; }">Delete</button>
            </form>
        </li>
        {% if job.isActivated %}
            <li {% if job.expiresSoon %} class="expires_soon" {% endif %}>
                {% if job.isExpired %}
                    Expired
                {% else %}
                    Expires in <strong>{{ job.getDaysBeforeExpires }}</strong> days
                {% endif %}

                {% if  job.expiresSoon %}
                    <form action="{{ path('ibw_job_extend', { 'token': job.token }) }}" method="post">
                        {{ form_widget(extend_form) }}
                        <button type="submit">Extend</button> for another 30 days
                    </form>
                {% endif %}
            </li>
        {% else %}
            <li>
                [Bookmark this <a href="{{ url('ibw_job_preview', { 'token': job.token, 'company': job.companyslug, 'location': job.locationslug, 'position': job.positionslug }) }}">URL</a> to manage this job in the future.]
            </li>
        {% endif %}
    </ul>
</div>

src/Ibw/JobeetBundle/Resources/views/Job/edit.html.twig
{% extends 'IbwJobeetBundle::layout.html.twig' %}
 
{% form_theme edit_form _self %}
 
{% block form_errors %}
    {% spaceless %}
        {% if errors|length > 0 %}
            <ul class="error_list">
                {% for error in errors %}
                    <li>{{ error.messageTemplate|trans(error.messageParameters, 'validators') }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endspaceless %}
{% endblock form_errors %}
 
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('bundles/ibwjobeet/css/job.css') }}" type="text/css" media="all" />
{% endblock %}
 
{% block content %}
    <h1>Job edit</h1>
<form action="{{ path('ibw_job_update', {'token': entity.token}) }}" method="post" {{ form_enctype(edit_form) }}>
    <table id="job_form">
        <tfoot>
        <tr>
            <td colspan="2">
                <input type="submit" value="Preview your job" />
            </td>
        </tr>
        </tfoot>
        <tbody>
        <tr>
            <th>{{ form_label(edit_form.category) }}</th>
            <td>
                {{ form_errors(edit_form.category) }}
                {{ form_widget(edit_form.category) }}
            </td>
        </tr>
        <tr>
            <th>{{ form_label(edit_form.type) }}</th>
            <td>
                {{ form_errors(edit_form.type) }}
                {{ form_widget(edit_form.type) }}
            </td>
        </tr>
        <tr>
            <th>{{ form_label(edit_form.company) }}</th>
            <td>
                {{ form_errors(edit_form.company) }}
                {{ form_widget(edit_form.company) }}
            </td>
        </tr>
        <tr>
            <th>{{ form_label(edit_form.file) }}</th>
            <td>
                {{ form_errors(edit_form.file) }}
                {{ form(edit_form.file) }}
            </td>
        </tr>
        <tr>
            <th>{{ form_label(edit_form.url) }}</th>
            <td>
                {{ form_errors(edit_form.url) }}
                {{ form_widget(edit_form.url) }}
            </td>
        </tr>
        <tr>
            <th>{{ form_label(edit_form.position) }}</th>
            <td>
                {{ form_errors(edit_form.position) }}
                {{ form_widget(edit_form.position) }}
            </td>
        </tr>
        <tr>
            <th>{{ form_label(edit_form.location) }}</th>
            <td>
                {{ form_errors(edit_form.location) }}
                {{ form_widget(edit_form.location) }}
            </td>
        </tr>
        <tr>
            <th>{{ form_label(edit_form.description) }}</th>
            <td>
                {{ form_errors(edit_form.description) }}
                {{ form_widget(edit_form.description) }}
            </td>
        </tr>
        <tr>
            <th>{{ form_label(edit_form.how_to_apply) }}</th>
            <td>
                {{ form_errors(edit_form.how_to_apply) }}
                {{ form_widget(edit_form.how_to_apply) }}
            </td>
        </tr>
        <tr>
            <th>{{ form_label(edit_form.is_public) }}</th>
            <td>
                {{ form_errors(edit_form.is_public) }}
                {{ form_widget(edit_form.is_public) }}
                <br /> Whether the job can also be published on affiliate websites or not.
            </td>
        </tr>
        <tr>
            <th>{{ form_label(edit_form.email) }}</th>
            <td>
                {{ form_errors(edit_form.email) }}
                {{ form_widget(edit_form.email) }}
            </td>
        </tr>
        </tbody>
    </table>
    {{ form_end(edit_form) }}
{% endblock %}

src/Ibw/JobeetBundle/Resources/views/Job/index.html.twig
{% extends 'IbwJobeetBundle::layout.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('bundles/ibwjobeet/css/jobs.css') }}" type="text/css" media="all" />
{% endblock %}

{% block content %}
    <div id="jobs">
        {% for category in categories %}
            <div>
                <div class="category">
                    <div class="feed">
                        <a href="">Feed</a>
                    </div>
                    <h1>
                        <a href="{{ path('IbwJobeetBundle_category', { 'slug': category.slug }) }}">
                            {{ category.name }}
                        </a>
                    </h1>
                </div>
                {{ include ('IbwJobeetBundle:Job:list.html.twig', {'jobs': category.activejobs}) }}
                {% if category.morejobs %}
                    <div class="more_jobs">
                        and <a href="{{ path('IbwJobeetBundle_category', { 'slug': category.slug }) }}">{{ category.morejobs }}</a>
                        more...
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    </div>
{% endblock %}

src/Ibw/JobeetBundle/Resources/views/Job/list.html.twig
<table class="jobs">
    {% for entity in jobs %}
        <tr class="{{ cycle(['even', 'odd'], loop.index) }}">
            <td class="location">{{ entity.location }}</td>
            <td class="position">
                <a href="{{ path('ibw_job_show', { 'company': entity.companyslug, 'location': entity.locationslug, 'id': entity.id, 'position': entity.positionslug }) }}">
                    {{ entity.position }}
                </a>
            </td>
            <td class="company">{{ entity.company }}</td>
        </tr>
    {% endfor %}
</table>

src/Ibw/JobeetBundle/Resources/views/Job/new.html.twig
{% extends 'IbwJobeetBundle::layout.html.twig' %}
 
{% form_theme form _self %}
 
{% block form_errors %}
    {% spaceless %}
        {% if errors|length > 0 %}
            <ul class="error_list">
                {% for error in errors %}
                    <li>{{ error.messageTemplate|trans(error.messageParameters, 'validators') }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endspaceless %}
{% endblock form_errors %}
 
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('bundles/ibwjobeet/css/job.css') }}" type="text/css" media="all" />
{% endblock %}
 
{% block content %}
    <h1>Job creation</h1>
<form action="{{ path('ibw_job_create') }}" method="post" {{ form_enctype(form) }}>
    <table id="job_form">
        <tfoot>
        <tr>
            <td colspan="2">
                <input type="submit" value="Preview your job" />
            </td>
        </tr>
        </tfoot>
        <tbody>
        <tr>
            <th>{{ form_label(form.category) }}</th>
            <td>
                {{ form_errors(form.category) }}
                {{ form_widget(form.category) }}
            </td>
        </tr>
        <tr>
            <th>{{ form_label(form.type) }}</th>
            <td>
                {{ form_errors(form.type) }}
                {{ form_widget(form.type) }}
            </td>
        </tr>
        <tr>
            <th>{{ form_label(form.company) }}</th>
            <td>
                {{ form_errors(form.company) }}
                {{ form_widget(form.company) }}
            </td>
        </tr>
        <tr>
            <th>{{ form_label(form.file) }}</th>
            <td>
                {{ form_errors(form.file) }}
                {{ form_widget(form.file) }}
            </td>
        </tr>
        <tr>
            <th>{{ form_label(form.url) }}</th>
            <td>
                {{ form_errors(form.url) }}
                {{ form_widget(form.url) }}
            </td>
        </tr>
        <tr>
            <th>{{ form_label(form.position) }}</th>
            <td>
                {{ form_errors(form.position) }}
                {{ form_widget(form.position) }}
            </td>
        </tr>
        <tr>
            <th>{{ form_label(form.location) }}</th>
            <td>
                {{ form_errors(form.location) }}
                {{ form_widget(form.location) }}
            </td>
        </tr>
        <tr>
            <th>{{ form_label(form.description) }}</th>
            <td>
                {{ form_errors(form.description) }}
                {{ form_widget(form.description) }}
            </td>
        </tr>
        <tr>
            <th>{{ form_label(form.how_to_apply) }}</th>
            <td>
                {{ form_errors(form.how_to_apply) }}
                {{ form_widget(form.how_to_apply) }}
            </td>
        </tr>
        <tr>
            <th>{{ form_label(form.is_public) }}</th>
            <td>
                {{ form_errors(form.is_public) }}
                {{ form_widget(form.is_public) }}
                <br /> Whether the job can also be published on affiliate websites or not.
            </td>
        </tr>
        <tr>
            <th>{{ form_label(form.email) }}</th>
            <td>
                {{ form_errors(form.email) }}
                {{ form_widget(form.email) }}
            </td>
        </tr>
        </tbody>
    </table>
    {{ form_end(form) }}
{% endblock %}

src/Ibw/JobeetBundle/Resources/views/Job/show.html.twig
{% extends 'IbwJobeetBundle::layout.html.twig' %}

{% block title %}
    {{ entity.company }} is looking for a {{ entity.position }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('bundles/ibwjobeet/css/job.css') }}" type="text/css" media="all" />
{% endblock %}

{% block content %}
    {% if app.request.get('token') %}
        {% include 'IbwJobeetBundle:Job:admin.html.twig' with {'job': entity} %}
    {% endif %}
    {% include 'IbwJobeetBundle:Job:admin.html.twig' with {'job': entity} %}
    <div id="job">
        <h1>{{ entity.company }}</h1>
        <h2>{{ entity.location }}</h2>
        <h3>
            {{ entity.position }}
            <small> - {{ entity.type }}</small>
        </h3>

        {% if entity.logo %}
            <div class="logo">
                <a href="{{ entity.url }}">
                    {% set a = entity.logo  %}
                    {% set b = "bundles/ibwjobeet/images/"  %}
                    <img src="{{ asset(b~a) }} "
                         style="max-height: 60px;max-width: 150px;"
                         alt="{{ entity.company }} logo" />
                </a>
            </div>
        {% endif %}

        <div class="description">
            {{ entity.description|nl2br }}
        </div>

        <h4>{% trans %}How to apply{% endtrans %}?</h4>

        <p class="how_to_apply">{{ entity.howtoapply }}</p>

        <div class="meta">
            <small>posted on {{ entity.createdat|date('m/d/Y') }}</small>
        </div>

        {#<div style="padding: 20px 0">
            <a href="{{ path('ibw_job_edit', {'token': entity.token}) }}">
                Edit
            </a>
        </div>#}
    </div>
{% endblock %}